### ISSUE TITLE
TempFolder path not found when not previously set

### ISSUE THREAD

**Issue by glitchroy** [nommiin/builder#1]
in `build.js`, a path to the GMS2TEMP folder is constructed using the `local_settings.json` in the user folder.
https://github.com/nommiin/builder/blob/e17c3fb96a8d279b73066cbdeca49bf8ec7c6702/build.js#L64

It just so happens that I've never set this path in the IDE itself, so my `local_settings.json` does not have the entry for `machine.General Settings.Paths.IDE.TempFolder` and it simply returns undefined and throws an error in the dev tools console. Setting the path to something different (in the GMS2 IDE under File > Preferences > General Settings > Paths > Temp directory) and then replacing it with the default again (`C:\Users\<USERNAME>\AppData\Local\GameMakerStudio2`) updated the `local_settings.json` accordingly.  
My guess would be to just assume the default path when the entry is not found, since it implies that the option was never changed to begin with. I don't know if that's the case for everyone or my `local_settings.json` is just messed up, though.

Great work on the plugin! This pushes GMEdit just one step closer to a full replacement for the IDE!

**Comment by nommiin** [comment]
Ah, good find! Thanks for reporting this issue, I've fixed it in this commit: ff7b306c5a86a354e638e536fee22bee5cad597f

Let me know if you run into any more issues, and thanks for the kind words ^_^
