### ISSUE TITLE
Run greyed out

### ISSUE THREAD

**Issue by MickGyver** [nommiin/builder#2]
Nice work on this one! I can't get the plugin to work though. "Run" is greyed out (with a project opened). I use Windows 7. If I go to builder settings and click Reload runtimes, I get an error  message saying: "The given runtime location does not exist!". The runtime location is correct.

**Comment by MickGyver** [comment]
Sorry, entirely my fault, I had opened the GMS1.4 version of the project by mistake, not the GMS2.x version.

**Comment by nommiin** [comment]
Sorry about that, hopefully soon I'll look into adding GMS1.4 support!
