### ISSUE TITLE
Selected runtime - string not being set via dropdown?

### ISSUE THREAD

**Issue by shinestrength** [nommiin/builder#3]
Had to manually fill in the runtime value in Builder-preferences.json - didn't seem to be being set via the dropdown?

**Comment by nommiin** [comment]
Odd, I looked into this more but couldn't reproduce it. If this happens again and you have steps to reproduce then feel free to let me know!

**Comment by nommiin** [comment]
I've made a potential fix to the issue, let me know if it occurs: => https://github.com/nommiin/builder/commit/ffaab083afd7784c9de438066a2ef137987173af
